language: java

jdk:
  - jdk-13.0.2

branches:
  only:
    - master
    - development

before_script:
  - cd seip2020_practical_assignments # Command to enter Maven root directory of the project
  - la -la # this command just prints the contents of the current working directory

script:
  - mvn clean package # Execute this command in the root maven directory and the project will be build

after_success:
  - echo "Process completed successfylly!"